logging.level:
#  org.springframework.context: WARN
#  org.springframework.data: WARN
#  org.springframework.jdbc: WARN
#  example: DEBUG
  ROOT: INFO

spring:

  web:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

  kafka:
    streams:
      state-store-cache-max-size: 100
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
management:
  endpoint:
    health:
      # [Spring Advisor]: This property disables health-group-membership-validation with boot 3.1 for backwards compatible reasons, but the Spring team encourages to enable it.

      validate-group-membership: false